# Generated by Django 5.1.3 on 2024-12-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_livro_capa"),
    ]

    operations = [
        migrations.AddField(
            model_name="editora",
            name="cidade",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="editora",
            name="email",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
