# Generated by Django 5.1.3 on 2024-12-16 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0017_compra_tipo_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="compras", to="core.user"
            ),
        ),
        migrations.AlterField(
            model_name="itenscompra",
            name="livro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="itens_compra", to="core.livro"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(blank=True, related_name="core_user_set", to="auth.group"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(blank=True, related_name="core_user_permissions_set", to="auth.permission"),
        ),
    ]
