# Generated by Django 5.1.3 on 2025-02-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_user_date_joined_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
