# Generated by Django 5.1.3 on 2025-02-12 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_compra_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="favorito",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="compra",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Carrinho"), (2, "Finalizado"), (3, "Pago"), (4, "Entregue")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="itenscompra",
            name="livro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="itenscompra", to="core.livro"
            ),
        ),
        migrations.AlterField(
            model_name="itenscompra",
            name="preco",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
